spring:
  profiles:
    active: local

---
spring:
  profiles: local
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql:  true
  datasource:
    url: jdbc:h2:mem:testdb